name: 'Deploy'

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    container: artronics/pipeline:0.1.6
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: version
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          deploy --bump=patch --github-context="$GITHUB_CONTEXT" --git-user-name="pipeline local" \
            --git-user-email="pipeline@pipeline.com"
