name: 'Deploy'

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    container: artronics/pipeline:0.0.2
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GIT_USERNAME: ${{ github.actor }}
      GIT_REMOTE_URL: ${{ github.repository }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: check
        run: |
          ls -la
          pwd
          echo $SHELL
          echo $GIT_USERNAME
          echo $GIT_REMOTE_URL
          echo https://github.com/${GIT_REMOTE_URL}.git
          ls -la /app
          
          git config --global user.email "pipeline@artronics.com"
          git config --global user.name "github-action pipeline"
          
          git-helper -u $GIT_USERNAME -p $GITHUB_TOKEN https://github.com/${GIT_REMOTE_URL}.git
          new_ver=$(version --bump patch)
          echo new version $new_ver
          poetry version $new_ver
          git commit -m "Bump version: $new_ver"
          git push pipeline master
          git tag $new_ver
          git push pipeline $new_ver
          
