name: 'Deploy'

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    container: artronics/pipeline:0.0.1
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GIT_USERNAME: ${{ github.actor }}
      GIT_REMOTE_URL: ${{ github.repository }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: check
        run: |
          ls -la
          pwd
          echo $GIT_USERNAME
          echo $GIT_REMOTE_URL
          echo https://github.com/${GITHUB_TOKEN}.git
          ls -la /app
          
          poetry install
          poetry run python vajeh_pipeline_docker/git_util.py -u $GIT_USERNAME -p $GITHUB_TOKEN -t 1.5.2 https://github.com/${GITHUB_TOKEN}.git
          
